name: smash-dev
channels:
    - conda-forge
dependencies:
    - python=3.11
    - pip

    # required dependencies
    - compilers
    - openjdk
    - meson
    - meson-python
    - ninja
    - numpy
    - f90wrap
    - versioneer[toml]
    - rasterio
    - pandas
    - h5py
    - tqdm
    - scipy
    - pyyaml
    - terminaltables

    # documentation
    - sphinx
    - numpydoc
    - pydata-sphinx-theme
    - ipython
    - pickleshare
    - sphinxcontrib-bibtex
    - sphinx-design
    - sphinx-autosummary-accessors
    - matplotlib

    # test
    - pytest
    - pytest-cov

    # format
    - ruff
    - fprettify
