name: smash-dev
channels:
    - conda-forge
dependencies:
    - python=3.11
    - pip

    # compile
    - make
    - gcc
    - gfortran

    # required dependencies
    - f90wrap
    - numpy>=1.25
    - pandas
    - matplotlib  # (optional: only used for plotting and visualization)
    - h5py>=3.9
    - tqdm
    - gdal
    - scipy
    - pyyaml
    - terminaltables

    # documentation
    - sphinx
    - numpydoc
    - pydata-sphinx-theme
    - ipython
    - sphinxcontrib-bibtex
    - sphinx-design
    - sphinx-autosummary-accessors

    # test
    - pytest

    # format
    - black
    - fprettify
